services:
  - type: web
    name: youtube-webhook
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DIFY_API_KEY
        value: app-qNlUdORdzpuxro4jssytJeZZ
      - key: DIFY_URL
        value: https://1qyow4mun8fb8n95.ai-plugin.io/single-workflow
      - key: WEBHOOK_SECRET
        value: app-qNlUdORdzpuxro4jssytJeZZ
